name: Android CI

on:
  pull_request:
    branches: [ master ]
env:
  API_KEY_PASSWORD: ${{secrets.API_KEY_PASSWORD }}
  SIGN_KEY_ALIAS: ${{secrets.SIGN_KEY_ALIAS}}
  SIGN_KEY_PASSWORD: ${{secrets.API_KEY_PASSWORD }}

jobs:
  build_apk:
    if: stratsWith(github.head_ref, 'release/') == true
    name: Build realease artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name:  Checkout API key repo
      uses: actions?checkout@v2
      with:
        reposytory: ${{secrets.API_KEY_REPO}}
        token: ${{secrets.API_KEY_ACCESS_TOKEN}}
        path: app/api_key 
        
        
    - name: Build realese
      run: |
        ./gradlew test
        ./gradlew assembleRelease
        ./gradlew bundelRelease
      
    - name: Upload APK
      uses: actions/uploadartifat@v2
      with:
        name: app-release.apk
        path: app/build/outputs/apk/realease/app-release-unsigned.apk
    - name: Upload AAB
      uses: actions/uploadartifat@v2
      with:
        name: app-release.aab
        path: app/build/outputs/apk/realease/app-release.aab
